#!/usr/bin/env sh
# This file is intended to be ran in the host OS and basically just passes the commands onto the TechnoCore service. 
. ./init.sh
services=
libs=
if [ -z $PROD ]; then
    services="-v $(pwd)/services:/var/lib/technocore/"
    libs="-v $(pwd)/lib:/usr/local/lib/technocore/"
fi
# https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume
#if [ IS WINDOW]; then
#    WEIRD_WINDOWS_SLASH=/
#fi


docker run \
    --rm \
    -it \
    -v ${WEIRD_WINDOWS_SLASH}$(pwd):/mnt/technocore/ \
    $services \
    $libs \
    -v ${WEIRD_WINDOWS_SLASH}/var/run/docker.sock:/var/run/docker.sock \
    -e SERVER_HOSTNAME=${HOSTNAME} \
    -e TECHNOCORE_ROOT=$TECHNOCORE_ROOT \
    -e HOST_SERVICES_DIR=${TECHNOCORE_SERVICES} \
    ${image_provider:-scififarms}/technocore:${TAG:-latest} \
    $@
