mqtt_i() {
    docker exec $containerId2 rabbitmqctl "$@"
}

initialize_mqtt() {
    echo "Initializing MQTT"
    # I have to pass in a custom config to start vault without TLS.
    containerId2=$(docker run -d -p 15672:15672 --hostname mqtt -v ${stackname}_mqtt:/var/lib/rabbitmq rabbitmq:3.7.4-management)
    sleep 15

    # TODO: Make this password be generated by Vault. 
    local password="FirstPassword"
    local response=$(mqtt_i add_user vault $password)
    echo -e "Response:\n$response"
    create_secret mqtt_vault_username vault
    create_secret mqtt_vault_password $password
}
#create_vault_user(){ }